// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjqtgfcpkwzqcrjevjaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqcXRnZmNwa3d6cWNyamV2amFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTY3MDIsImV4cCI6MjA3MzUzMjcwMn0.SvU-oe1jP0gX1y4QC58wkF_pf4cSXFGDwb33enYq0UA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});